Repository ESPOL-FICT-PETROLEOS/PYTANK, pull requests merged in 2024-06, with the labels that each got.

#43 features-erick
  new/get_press_avg.py
  new/get_wells.py
  new/tank.py
  old/functions/eda.py
Labels: enhancement

#44 Update files
  new/fluid.py
  new/get_press_avg.py
  new/get_wells.py
  old/functions/eda.py
Labels: enhancement

#45 uw and avg_press methods
  new/constants.py
  new/fluid.py
  new/get_press_avg.py
  new/get_wells.py
  new/tank.py
  old/functions/eda.py
Labels: enhancement

#47 UW per Well
  old/daraframes/Dataframe_press_avg.py
  old/daraframes/eda.py
  old/daraframes/mbal_Dataframe.py
  old/daraframes/press_avg.csv
  old/daraframes/pressures.csv
  old/daraframes/production.csv
  old/daraframes/pruebablance.py
  pytank/__init__.py
  pytank/notebooks/get_wells.py
  pytank/tank/tank.py
Labels: enhancement

#48 Improve directories
  old/dataframes/Dataframe_press_avg.py
  old/dataframes/Oil_correlations.py
  old/dataframes/eda.py
  old/dataframes/mbal_Dataframe.py
  old/dataframes/metodo_cartertracy.py
  old/dataframes/press_avg.csv
  old/dataframes/pressures.csv
  old/dataframes/production.csv
  old/dataframes/pruebablance.py
  old/dataframes/pvt.csv
  old/dataframes/pvt_table.py
  old/dataframes/test_material_balance.py
  old/explorer/explore_data_analysis.py
  old/tests/test_for_functions.py
  old/utilities/Utilities.py
  pytank/functions/material_balance.py
  pytank/functions/optional_functions.py
  pytank/functions/pvt_interp.py
  pytank/functions/utilities.py
Labels: enhancement

#50 changues
  old/dataframes/Dataframe_press_avg.py
  old/dataframes/eda.py
  old/dataframes/mbal_Dataframe.py
  old/dataframes/production.csv
  pytank/notebooks/get_mat_ball.py
  pytank/resources/data_csv/production.csv
  pytank/tank/tank.py
Labels: enhancement

#51 update
  pytank/tank/tank.py
Labels: enhancement

#52 update
  pytank/tank/tank.py
Labels: enhancement

#53 GMethod
  pytank/tank/pruebablance.py
  pytank/tank/tank.py
Labels: enhancement

#54 test G_method
  poetry.lock
  pyproject.toml
  pytank/aquifer/influx_of_water.py
  pytank/functions/function2.py
  pytank/functions/material_balance.py
  pytank/functions/metodo_analitico.py
  pytank/functions/pvt_interp.py
  pytank/tank/pruebablance.py
  pytank/tank/tank.py
Labels: enhancement

#55 Calculated POES, graphic method
  pytank/aquifer/prueba_acuiferos.py
  pytank/functions/function2.py
  pytank/tank/tank.py
Labels: enhancement

#56 update we function
  pytank/aquifer/we.py
  pytank/tank/tank.py
Labels: enhancement

#57 POES
  pytank/POES.py
  pytank/constants/constants.py
  pytank/functions/function2.py
  pytank/functions/material_balance.py
  pytank/functions/pvt_interp.py
  pytank/tank/pruebablance.py
  pytank/tank/tank.py
Labels: enhancement

#58 Validation of dataframes
  pytank/POES.py
  pytank/fluid_model/fluid.py
  pytank/notebooks/quick_test_poes.py
  pytank/notebooks/quick_test_tank.py
  pytank/poes/__init__.py
  pytank/poes/poes.py
  pytank/tank/tank.py
Labels: enhancement

#59 POES (Tests)
  old/dataframes/mbal_Dataframe.py
  old/dataframes/test_material_balance.py
  pytank/aquifer/we.py
  pytank/constants/constants.py
  pytank/notebooks/qt_materialbal.py
  pytank/notebooks/quick_test_poes.py
  pytank/notebooks/quick_test_tank.py
  pytank/poes/poes.py
  pytank/tank/tank.py
Labels: enhancement

#60 Update fluid class
  pytank/fluid_model/fluid.py
  pytank/functions/pvt_correlations.py
Labels: enhancement

#62 Poes, Campbell
  pytank/fluid_model/fluid.py
  pytank/functions/material_balance.py
  pytank/notebooks/quick_test_poes.py
  pytank/notebooks/quick_test_tank.py
  pytank/tank/tank.py
Labels: enhancement

#64 EDA PLOTS
  pytank/analysis/poes.py
  pytank/notebooks/quick_test_analysis.py
  pytank/notebooks/quick_test_eda.py
  pytank/notebooks/quick_test_tank.py
  pytank/tank/tank.py
Labels: enhancement

#65 Update Well Class and test implementation
  pytank/constants/constants.py
  pytank/notebooks/get_wells.py
  pytank/notebooks/quick_test_analysis.py
  pytank/notebooks/quick_test_eda.py
  pytank/notebooks/quick_test_tank.py
  pytank/tank/tank.py
  pytank/vector_data/vector_data.py
  pytank/well/well.py
Labels: enhancement

#66 Well class
  pytank/well/well.py
Labels: enhancement

#67 Class Analytic Method
  pytank/analysis/poes.py
  pytank/aquifer/aquifer_model.py
  pytank/functions/function2.py
  pytank/functions/metodo_analitico.py
  pytank/functions/pvt_correlations.py
  pytank/notebooks/metodo_cartertracy.py
  pytank/notebooks/pruebablance.py
  pytank/notebooks/quick_test_analysis.py
  pytank/notebooks/quick_test_eda.py
  pytank/notebooks/quick_test_tank.py
  pytank/well/well.py
  tests/test1.py
Labels: enhancement

#68 Documentation (directories)
  pytank/analysis/poes.py
  pytank/aquifer/aquifer_model.py
  pytank/aquifer/we.py
  pytank/constants/constants.py
  pytank/fluid_model/fluid.py
  pytank/functions/Oil_correlations.py
  pytank/functions/function2.py
  pytank/functions/material_balance.py
  pytank/functions/metodo_analitico.py
  pytank/functions/pvt_correlations.py
  pytank/functions/pvt_interp.py
  pytank/functions/pvt_table.py
  pytank/functions/utilities.py
  pytank/notebooks/explore_data_analysis.py
  pytank/notebooks/get_mat_ball.py
  pytank/notebooks/get_press_avg.py
  pytank/notebooks/get_wells.py
  pytank/notebooks/mat_bal_implementation.py
  pytank/notebooks/pruebablance.py
  pytank/notebooks/quick_test_analysis.py
  pytank/notebooks/quick_test_eda.py
  pytank/notebooks/quick_test_mbal_functions.py
  pytank/notebooks/quick_test_tank.py
  pytank/notebooks/quick_test_vector_data.py
  pytank/tank/tank.py
  pytank/vector_data/vector_data.py
  pytank/well/well.py
  tests/test_for_functions.py
Labels: documentation, enhancement

#69 Update class and functions
  pytank/analysis/poes.py
  pytank/aquifer/aquifer_model.py
  pytank/functions/material_balance.py
  pytank/notebooks/metodo_cartertracy.py
  pytank/notebooks/quick_test_analysis.py
  pytank/notebooks/quick_test_eda.py
  pytank/notebooks/quick_test_tank.py
Labels: enhancement

#70 Analysis Class Improvement
  pytank/analysis/poes.py
  pytank/aquifer/aquifer_model.py
  pytank/notebooks/mat_bal_implementation.py
  pytank/notebooks/metodo_cartertracy.py
  pytank/notebooks/quick_test_analysis.py
  pytank/notebooks/quick_test_eda.py
  pytank/notebooks/quick_test_tank.py
  pytank/resources/data_csv/prueba.csv
Labels: enhancement

#71 General Improvement
  pytank/analysis/poes.py
  pytank/notebooks/mat_bal_implementation.py
  pytank/notebooks/quick_test_analysis.py
Labels: enhancement

#72 update docstrings
  pytank/analysis/poes.py
  pytank/aquifer/aquifer_model.py
  pytank/functions/material_balance.py
Labels: enhancement

#73 Analysis and Aquifer Model Improvement
  pytank/analysis/poes.py
  pytank/aquifer/aquifer_model.py
  pytank/notebooks/mat_bal_implementation.py
  pytank/notebooks/quick_test_analysis.py
  pytank/tank/tank.py
  pytank/well/well.py
Labels: enhancement

#74 Update class Wells
  pytank/aquifer/aquifer_model.py
  pytank/notebooks/mat_bal_implementation.py
  pytank/well/well.py
Labels: enhancement

#75 Documentations for class and functions
  pytank/analysis/poes.py
  pytank/functions/material_balance.py
  pytank/notebooks/mat_bal_implementation.py
  pytank/well/well.py
Labels: duplicate, enhancement
